--        PRIMARY KEY PEOPLE TABLE
ALTER TABLE people
ADD
CONSTRAINT pk_people PRIMARY KEY (id_people)
USING INDEX
TABLESPACE ge_ind PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

--         PRIMARY KEY  PHONE TABLE

ALTER TABLE phone
ADD
CONSTRAINT pk_phone PRIMARY KEY (id_phone)
USING INDEX
TABLESPACE ge_ind PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

--         FOREIGN KEY PHONE TABLE

ALTER TABLE phone
ADD
CONSTRAINT fk_phone_people FOREIGN KEY (id_people) REFERENCES people(id_people);